# Generated by Django 2.2.1 on 2020-07-24 19:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('askit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='question',
        ),
    ]
