# Generated by Django 2.2.1 on 2020-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('askit', '0002_auto_20200724_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
