# Generated by Django 2.2.1 on 2020-07-26 18:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('askit', '0003_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
