# Generated by Django 2.2.1 on 2020-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('askit', '0006_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='upvote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
