# Generated by Django 2.2.1 on 2020-07-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('askit', '0007_upvote_upvote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askit.Post')),
                ('upvote_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askit.Upvote')),
            ],
        ),
    ]
