# Generated by Django 2.2.1 on 2020-07-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('askit', '0009_auto_20200729_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Upvote',
            new_name='Upvote',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
