# Generated by Django 2.2.1 on 2020-07-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0010_auto_20200729_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upvote',
            new_name='Post_Upvote',
        ),
    ]
