# Generated by Django 2.2.1 on 2020-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0013_post_response_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='response_upvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='response_upvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
