# Generated by Django 2.2.1 on 2021-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askit', '0017_auto_20210122_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
